"""Cross-language crypto interop: known-answer tests against the frozen vectors.

Loads ``tests/crypto-vectors.json`` (generated by the TypeScript reference) and
asserts the Python crypto impl reproduces every vector byte-for-byte. This is
the interop proof: the ``sign`` vectors pin exact ed25519 ``sig`` bytes over JCS
input, so passing them means Python's JCS + ed25519 match TS exactly.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import pytest

from nbus.crypto import (
    Keypair,
    b64u_decode,
    canonicalize,
    decrypt,
    open_signed_encrypted,
    sign,
    verify_signed,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
VECTORS_PATH = REPO_ROOT / "tests" / "crypto-vectors.json"


def _load() -> list[dict[str, Any]]:
    data = json.loads(VECTORS_PATH.read_text())
    return [v for v in data if not v["kind"].startswith("_")]


VECTORS = _load()


def _by_kind(kind: str) -> list[dict[str, Any]]:
    return [v for v in VECTORS if v["kind"] == kind]


def _ids(vs: list[dict[str, Any]]) -> list[str]:
    return [v["name"] for v in vs]


# --------------------------------------------------------------------------- #
# jcs — canonicalize(input) == output (exact string)
# --------------------------------------------------------------------------- #

_JCS = _by_kind("jcs")


@pytest.mark.parametrize("v", _JCS, ids=_ids(_JCS))
def test_jcs(v: dict[str, Any]) -> None:
    got = canonicalize(v["input"]).decode("utf-8")
    assert got == v["output"]


# --------------------------------------------------------------------------- #
# sign — pub, sig, and signingInput all exact (the interop headline)
# --------------------------------------------------------------------------- #

_SIGN = _by_kind("sign")


@pytest.mark.parametrize("v", _SIGN, ids=_ids(_SIGN))
def test_sign(v: dict[str, Any]) -> None:
    kp = Keypair.ed25519_from_seed_b64(v["seed"])
    assert kp.public_key_b64 == v["expect"]["pub"]

    env = sign(v["payload"], kp, v["ts"])
    # Reconstruct the signing input the SAME way and prove it matches the vector.
    from nbus.crypto import _signing_bytes  # noqa: PLC0415 - test-internal

    signing_input = _signing_bytes(env["pub"], env["ts"], v["payload"]).decode()
    assert signing_input == v["expect"]["signingInput"]
    assert env["sig"] == v["expect"]["sig"]


# --------------------------------------------------------------------------- #
# verify — ok / reason substring
# --------------------------------------------------------------------------- #

_VERIFY = _by_kind("verify")


@pytest.mark.parametrize("v", _VERIFY, ids=_ids(_VERIFY))
def test_verify(v: dict[str, Any]) -> None:
    skew = v["maxSkewSeconds"]
    if skew is None:
        skew = math.inf
    res = verify_signed(v["envelope"], skew, v["now"])
    exp = v["expect"]
    assert res.ok is exp["ok"]
    if exp["ok"]:
        assert res.pub == exp["pub"]
    elif "reason_contains" in exp:
        assert exp["reason_contains"] in (res.reason or "")


# --------------------------------------------------------------------------- #
# decrypt — replay recorded e1 → plaintext
# --------------------------------------------------------------------------- #

_DECRYPT = _by_kind("decrypt")


@pytest.mark.parametrize("v", _DECRYPT, ids=_ids(_DECRYPT))
def test_decrypt(v: dict[str, Any]) -> None:
    recip = Keypair.x25519_from_raw_b64(v["recipientPriv"])
    res = decrypt(v["envelope"], recip)
    exp = v["expect"]
    assert res.ok is exp["ok"]
    if exp["ok"]:
        assert res.payload == exp["payload"]


# --------------------------------------------------------------------------- #
# open — sign-then-encrypt
# --------------------------------------------------------------------------- #

_OPEN = _by_kind("open")


@pytest.mark.parametrize("v", _OPEN, ids=_ids(_OPEN))
def test_open(v: dict[str, Any]) -> None:
    recip = Keypair.x25519_from_raw_b64(v["recipientPriv"])
    skew = v["maxSkewSeconds"]
    if skew is None:
        skew = math.inf
    res = open_signed_encrypted(v["envelope"], recip, skew, v["now"])
    exp = v["expect"]
    assert res.ok is exp["ok"]
    if exp["ok"]:
        assert res.pub == exp["pub"]
        assert res.payload == exp["payload"]
    elif "reason_contains" in exp:
        assert exp["reason_contains"] in (res.reason or "")


def test_seed_length_sanity() -> None:
    # Guard: vectors' seeds decode to 32 bytes (base64url no-pad).
    for v in _SIGN:
        assert len(b64u_decode(v["seed"])) == 32
